version: "3.8"

services:
    server:
        build: .
        container_name: vecbro
        restart: always
        ports:
            - "${SERVER_PORT}:3000"
        env_file:
            - ./.env
